export const GET_POLLS = 'GET_POLLS'
export const GET_POLL = 'GET_POLL'
export const ADD_POLL = 'ADD_POLL'
export const REMOVE_POLL = 'REMOVE_POLL'
export const EDIT_POLL = 'EDIT_POLL'
export const GET_EMO = 'GET_EMO'

export const CREATE_VOTE = 'CREATE_VOTE'
export const UPDATE_VOTE = 'UPDATE_VOTE'
export const GET_VOTE = 'GET_VOTE'
export const REMOVE_VOTE = 'GET_VOTE'

export const GET_COMMENT = 'GET_COMMENT'
export const DELETE_COMMENTS_BYVOTE = 'DELETE_COMMENTS_BYVOTE'
export const DELETE_COMMENTS_BYUSER = 'DELETE_COMMENTS_BYUSER'
export const UPDAET_COMMENT = 'UPDATE_COMMENT'
export const CREATE_COMMENT = 'CREATE_COMMENT'
